# Generated by Django 5.2.8 on 2025-11-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Market_Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("accessories", "Accessories"),
                            ("fashion", "Fashion"),
                            ("electronics", "Electronics"),
                        ],
                        max_length=30,
                    ),
                ),
                ("price", models.FloatField()),
                ("stock", models.IntegerField()),
                ("description", models.TimeField()),
                ("is_available", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
